##############################################################################
# Dockerfile de construcao do container APP com os pacotes basicos 
##############################################################################

ARG VERSION=latest
ARG OICD_VERSION=23.26.1.0.0
ARG TARGETPLATFORM
FROM socheatsok78/oracle-instantclient:${OICD_VERSION}-basic AS instantclient


FROM processoeletronico/sei5-alpine:${VERSION}
ARG OICD_VERSION
ARG TARGETPLATFORM

# Final
ENV PATH=/opt/oracle/instantclient:$PATH
ENV LD_LIBRARY_PATH=/opt/oracle/instantclient
ENV ORACLE_HOME=/opt/oracle/instantclient
COPY --from=instantclient /opt/oracle /opt/oracle

RUN apk --no-cache add gcompat libaio libnsl make curl php82-pear php82-dev gcc musl-dev && \
    folder=$(echo "$OICD_VERSION" | tr -d '.') && \
    if [ "$TARGETPLATFORM" = "linux/arm64" ]; then PLATFORM=arm64; else PLATFORM=x64; fi && \
    curl -v -o instantclient-sdk.zip "https://download.oracle.com/otn_software/linux/instantclient/$folder/instantclient-sdk-linux.$PLATFORM-$OICD_VERSION.zip" -SL && \
    unzip -o instantclient-sdk.zip && \
    mv -f instantclient*/* /opt/oracle/instantclient && \
    rm instantclient-sdk.zip && \
    echo "instantclient,${ORACLE_HOME}" | pecl82 install oci8 &&\
    echo 'extension=oci8.so' > /etc/php82/conf.d/30-oci8.ini &&\
    apk del make php82-pear php82-dev gcc musl-dev && \
    rm -rf /tmp/*.zip /var/cache/apk/* /tmp/pear/ ${ORACLE_HOME}/sdk

# Em DEV vários módulos esperam que esteja no root
# USER apache
EXPOSE 8000
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/sh", "-c", "crond && php-fpm82 -D && httpd -DFOREGROUND"]
