##############################################################################
# Dockerfile de construcao do container APP com os pacotes basicos 
##############################################################################
ARG VERSION=processoeletronico/sei5-alpine:latest
ARG TARGETPLATFORM
FROM ${VERSION}

# Permite o uso do SQLSERVER mas não funciona corretamente devido ao requisito de iso88591 do SEI
RUN apk add --no-cache --virtual .build-deps php82-dev make gcc g++ autoconf php82-pear unixodbc-dev gnupg \
   && if [ "$TARGETPLATFORM" = "linux/arm64" ]; then PLATFORM=arm64; else PLATFORM=amd64; fi \
   && curl -O "https://download.microsoft.com/download/3/5/5/355d7943-a338-41a7-858d-53b259ea33f5/msodbcsql18_18.3.2.1-1_$PLATFORM.apk" \
   && curl -O "https://download.microsoft.com/download/3/5/5/355d7943-a338-41a7-858d-53b259ea33f5/mssql-tools18_18.3.1.1-1_$PLATFORM.apk" \
   && curl -O "https://download.microsoft.com/download/3/5/5/355d7943-a338-41a7-858d-53b259ea33f5/msodbcsql18_18.3.2.1-1_$PLATFORM.sig" \
   && curl -O "https://download.microsoft.com/download/3/5/5/355d7943-a338-41a7-858d-53b259ea33f5/mssql-tools18_18.3.1.1-1_$PLATFORM.sig" \
   && curl https://packages.microsoft.com/keys/microsoft.asc  | gpg --import - \
   && gpg --verify "msodbcsql18_18.3.2.1-1_$PLATFORM.sig" "msodbcsql18_18.3.2.1-1_$PLATFORM.apk" \
   && gpg --verify "mssql-tools18_18.3.1.1-1_$PLATFORM.sig" "mssql-tools18_18.3.1.1-1_$PLATFORM.apk" \
   && apk add --allow-untrusted "msodbcsql18_18.3.2.1-1_$PLATFORM.apk" "mssql-tools18_18.3.1.1-1_$PLATFORM.apk" \
   && rm *.apk *.sig \
   && apk add --no-cache unixodbc \
   && pecl82 install pdo_sqlsrv-5.12.0 sqlsrv-5.12.0 \
   && apk del .build-deps \
   && echo 'extension=sqlsrv.so' > /etc/php82/conf.d/98_sqlserver.ini \
   && echo 'extension=pdo_sqlsrv.so' > /etc/php82/conf.d/99_sqlserver.ini

# Em DEV vários módulos esperam que esteja no root
# USER apache
EXPOSE 8000
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/sh", "-c", "crond && php-fpm82 -D && httpd -DFOREGROUND"]
