[opcache]

opcache.enable=1
opcache.enable_cli=0

opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
; Para validar timestamp. 
; Em produção deve ser 0 para melhorar performance
opcache.validate_timestamps=1
opcache.revalidate_freq=2

opcache.fast_shutdown=1
opcache.save_comments=1

opcache.jit=off