name: Publica images e SBOM

on:
  push:
    branches:
      - "main"
    paths:
      - 'Dockerfile'
      - 'Dockerfile-oracle'
      - 'Dockerfile-sqlserver'
      - 'assets/**'
      - '.github/workflows/publish.yml'
    tags:
      - "*.*.*"
jobs:
  docker:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        image: [processoeletronico/sei5-alpine, processoeletronico/sei5-alpine-oracle, processoeletronico/sei5-alpine-sqlserver]
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
            versao: x64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            versao: arm64
          - image: processoeletronico/sei5-alpine
            dockerfile: Dockerfile
          - image: processoeletronico/sei5-alpine-oracle
            dockerfile: Dockerfile-oracle
          - image: processoeletronico/sei5-alpine-sqlserver
            dockerfile: Dockerfile-sqlserver

    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v6
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=pep440,pattern={{version}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: ${{ matrix.platform }}
          file: ${{ matrix.dockerfile }}
          sbom: true
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=build-${{ env.PLATFORM_PAIR }}
          cache-to: type=gha,scope=build-${{ env.PLATFORM_PAIR }}
          build-args: |
            "PLATFORM=${{ matrix.versao }}"
            "OICD_VERSION=23.26.1.0.0"
      - name: Docker Scout
        uses: docker/scout-action@v1.20.2
        with:
          command: cves,recommendations
          image: ${{ matrix.image }}
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          sarif-file: sarif.output.json
          summary: true
      - name: Upload SARIF result
        id: upload-sarif
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: sarif.output.json
